# Generated by Django 4.0.4 on 2022-12-16 19:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias_category', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('active', models.BooleanField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('product_code', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('detai', models.TextField()),
                ('image', models.ImageField(null=True, upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('category_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='degray.category')),
                ('created', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_user', models.IntegerField()),
                ('name_cus', models.CharField(max_length=255)),
                ('email_cus', models.EmailField(max_length=254)),
                ('phone_cus', models.CharField(max_length=255)),
                ('address_cus', models.TextField()),
                ('status', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('note', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Receipt_DeTail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_item', models.CharField(max_length=255)),
                ('item_size', models.CharField(max_length=255, null=True)),
                ('qty_item', models.IntegerField()),
                ('price', models.BigIntegerField()),
                ('image', models.ImageField(upload_to='')),
                ('id_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='degray.item')),
                ('id_receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='degray.receipt')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255)),
                ('item_size', models.CharField(max_length=255, null=True)),
                ('qty', models.IntegerField()),
                ('add_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('user_add', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
