# Generated by Django 4.0.4 on 2022-12-16 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('degray', '0002_cart_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='image',
            field=models.ImageField(default=None, upload_to=''),
        ),
    ]
