# Generated by Django 4.0.4 on 2022-12-19 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('degray', '0006_alter_receipt_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipt_detail',
            name='id_item',
        ),
    ]
