# Generated by Django 4.0.4 on 2022-12-20 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('degray', '0008_alter_receipt_detail_id_receipt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='status',
            field=models.CharField(choices=[('1', 'Đã Khởi Tạo'), ('2', 'Đang Giao Hàng'), ('3', 'Giao Thành Công'), ('4', 'Bị Hủy')], default=1, max_length=255),
        ),
    ]
